# Generated by Django 4.2 on 2024-09-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='first_name',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(default='unknown', max_length=40),
        ),
    ]
