# Generated by Django 4.2 on 2024-09-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='user',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='first_name',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='last_name',
            field=models.CharField(default='unknown', max_length=40),
        ),
    ]
