# Generated by Django 4.2 on 2024-09-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0002_remove_mechanic_rating_remove_mechanic_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
    ]
